[package]
name = "reflex-cli"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Marshall Wace LLP <opensource@mwam.com>", "Tim Kendrick <t.kendrick@mwam.com>", "Jordan Hall <j.hall@mwam.com>", "Chris Campbell <c.campbell@mwam.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reflex = { path = "../reflex" }
reflex-handlers = { path = "../reflex-handlers" }
reflex-loaders = { path = "../reflex-loaders" }
reflex-js = { path = "../reflex-js" }
reflex-runtime = { path = "../reflex-runtime" }
tokio = { version = "1", features = ["full"] }
